name: hackathon-tim-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy==1.26.4
      - pandas==2.2.3
      - scikit-learn==1.5.2
      - torch==2.4.1
      - pytest==9.1.1
